#!/bin/sh
# Filename:      grml-feedback
# Purpose:       give feedback to grml
# Author:        Martin Scharm <martin@binfalse.de>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Sun Mar 12 18:00:00 CEST 2011
################################################################################

. /etc/grml/script-functions

[ -f /etc/grml_version ] && URL_PARAMS="?version=$(awk '{print $2}' /etc/grml_version)"
FEEDBACKURL=${FEEDBACKURL:-http://feedback.grml.org/submit-feedback$URL_PARAMS}

usage() {
cat >&2 <<EOF
grml-feedback - give feedback to the Grml project
USAGE: $0 [-u URL]

  -u URL       browse to URL, default: $FEEDBACKURL

EOF
}

while getopts 'u:h' OPTION ; do
  case $OPTION in
    u) FEEDBACKURL=$OPTARG;;
    h) usage; exit 1;;
    *) usage; exit 1;;
  esac
done

if [ -n "${DISPLAY}" ]; then
    x-www-browser $FEEDBACKURL &
else
    www-browser $FEEDBACKURL
fi

